import type { Snapshot, DriftReport } from './types';
import type { ReviewResult } from '@/lib/config-review/runner';
import type { BootstrapBudget } from '@/lib/config-review/types';

/**
 * Generate a human-readable markdown summary of a scan session.
 */
export function generateSessionNotes(
  review: ReviewResult,
  budget: BootstrapBudget,
  snapshot: Snapshot,
  drift: DriftReport | null,
): string {
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });
  const lines: string[] = [];

  lines.push(`# Driftwatch Session Notes — ${date}`);
  lines.push('');

  // Health score
  const scoreEmoji = review.healthScore >= 90 ? '✅' : review.healthScore >= 70 ? '⚠️' : '🔴';
  lines.push(`## Health Score: ${review.healthScore}/100 ${scoreEmoji}`);
  lines.push('');

  // Bootstrap budget
  const budgetPct = Math.round((budget.totalChars / budget.budgetLimit) * 100);
  lines.push(`## Bootstrap Budget: ${budget.totalChars.toLocaleString()} / ${budget.budgetLimit.toLocaleString()} chars (${budgetPct}%)`);
  lines.push(`~${Math.ceil(budget.totalChars / 4).toLocaleString()} tokens injected per message`);
  lines.push('');

  // Findings by severity
  if (review.findings.length > 0) {
    lines.push('## Findings');
    lines.push('');

    const crits = review.findings.filter(f => f.severity === 'critical');
    const warns = review.findings.filter(f => f.severity === 'warning');
    const infos = review.findings.filter(f => f.severity === 'info');

    if (crits.length > 0) {
      lines.push(`### 🔴 Critical (${crits.length})`);
      for (const f of crits) lines.push(`- **${f.file}**: ${f.message}`);
      lines.push('');
    }
    if (warns.length > 0) {
      lines.push(`### 🟡 Warning (${warns.length})`);
      for (const f of warns) lines.push(`- **${f.file}**: ${f.message}`);
      lines.push('');
    }
    if (infos.length > 0) {
      lines.push(`### 🔵 Info (${infos.length})`);
      for (const f of infos) lines.push(`- **${f.file}**: ${f.message}`);
      lines.push('');
    }
  } else {
    lines.push('## Findings: None ✅');
    lines.push('');
  }

  // Drift report
  if (drift) {
    lines.push('## Changes Since Last Scan');
    lines.push(`Previous scan: ${new Date(drift.previousTimestamp).toLocaleDateString()} (${drift.daysBetween} days ago)`);
    lines.push('');

    if (drift.filesAdded.length > 0) lines.push(`- **Added:** ${drift.filesAdded.join(', ')}`);
    if (drift.filesRemoved.length > 0) lines.push(`- **Removed:** ${drift.filesRemoved.join(', ')}`);
    if (drift.filesChanged.length > 0) {
      lines.push(`- **Changed:** ${drift.filesChanged.length} file${drift.filesChanged.length !== 1 ? 's' : ''}`);
      for (const f of drift.filesChanged) {
        const dir = f.charCountDelta >= 0 ? '+' : '';
        lines.push(`  - ${f.path}: ${dir}${f.charCountDelta.toLocaleString()} chars (${f.percentGrowth >= 0 ? '+' : ''}${f.percentGrowth.toFixed(1)}%)`);
      }
    }
    if (drift.healthScoreDelta !== 0) {
      const dir = drift.healthScoreDelta > 0 ? '+' : '';
      lines.push(`- **Health score:** ${dir}${drift.healthScoreDelta} points`);
    }
    if (drift.budgetDelta !== 0) {
      const dir = drift.budgetDelta > 0 ? '+' : '';
      lines.push(`- **Budget:** ${dir}${drift.budgetDelta.toLocaleString()} chars`);
    }
    lines.push('');
  }

  // Top recommendations
  const topFindings = review.findings.filter(f => f.severity !== 'info').slice(0, 3);
  if (topFindings.length > 0) {
    lines.push('## Top Recommendations');
    for (const f of topFindings) {
      lines.push(`1. ${f.recommendation}`);
    }
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push(`*Generated by Driftwatch • ${snapshot.files.length} files analyzed • ${review.rulesExecuted} rules checked*`);

  return lines.join('\n');
}
